alias i3conf="vim ~/.config/i3/config"
alias config='/usr/bin/git --git-dir=/home/josh/.cfg/ --work-tree=/home/josh'
alias light="sudo enlighten"
alias untar="tar -xvzf"
alias ex="chmod +x"
alias wp="feh --randomize --bg-scale"
alias cdcode="cd ~/Dropbox/Code"
alias cdbr="cd ~/Dropbox/Code/BrainGridLock"
alias r="R"
alias bats="BATS_RUN_SKIPPED=true bats"
