# This config is focused on classified names.
#
# When a new client is spawned, it checks its name against
# any of the classifiers.  If there's a match, it will use
# the name specified.  If not, the desktop name will be
# a space separated string of opened clients.  All empty
# desktops will use the constant name

min = 10
max = 10
remove-empty = true
watch-config = true
append-when-occupied = true
renamers = ["classified", "client", "constant"]

[names]
constant = ""

[[names.classified]]
"" = ["firefox"]
"" = ["Emacs"]
"" = ["email", "Thunderbird"]
"" = ["Steam"]
"" = ["Spotify"]
"" = ["Zathura"]
"" = ["libreoffice-writer"]
"" = ["libreofice-impress"]
"" = ["Caprine"]
"" = ["Deluge", "Deluge-gtk"]
"" = ["Thunar", "ranger"]
"" = ["Wine"]
"" = ["Alacritty"]