#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

fg_color=$(xrdb -query | grep -m1 foreground | awk '{ print $2 }')
bg_color=$(xrdb -query | grep -m1 background | awk '{ print $2 }')

bspc config focused_border_color  "$fg_color"
bspc config presel_feedback_color "$bg_color"
bspc config normal_border_color   "$bg_color"
bspc config active_border_color   "$bg_color"

# RULES
bspc rule -a firefox desktop='^2' state=pseudo_tiled rectangle=1800x1200+0+0 center=true
bspc rule -a Emacs state=pseudo_tiled rectangle=850x1100+0+0
bspc rule -a Spotify desktop='^4'
bspc rule -a Alacritty state=pseudo_tiled rectangle=800x600+0+0 center=true
bspc rule -a ncspot state=pseudo_tiled desktop='^4'
bspc rule -a email state=pseudo_tiled desktop='^3' rectangle=1200x900+0+0
bspc rule -a feh state=floating rectangle=1200x800+0+0 center=true
bspc rule -a Caprine state=pseudo_tiled rectangle=1200x900+0+0

# startup applications
sxhkd &
kill_and_restart_apps &
setxkbmap -option caps:escape &
unclutter &
wal -R &
compton -f &
emacs --daemon &
xautolock -time 10 -locker betterlockscreen -l dim &
xinput set-prop 12 276 1 & # touchpad settings
xinput set-prop 12 298 1 &
