#! /bin/sh

# startup applications
sxhkd &
polybarstart &
# ~/bin/rebind_caps_to_escape &
setxkbmap -option caps:escape &
unclutter &
compton -f &
emacs --daemon &
dropbox &
redshift-gtk &
nm-applet &
wal -R &
btops &
xautolock -time 10 -locker betterlockscreen -l dim &
xinput set-prop 12 276 1 & # touchpad settings
xinput set-prop 12 298 1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2' state=pseudotiled follow=off

fg_color=$(xrdb -query | grep -m1 foreground | awk '{ print $2 }')
bg_color=$(xrdb -query | grep -m1 background | awk '{ print $2 }')

bspc config focused_border_color  "$fg_color"
bspc config presel_feedback_color "$fg_color"
bspc config normal_border_color   "$bg_color"
bspc config active_border_color   "$bg_color"
